isomerpages/moe-eastspringsec

- _school-information/2023 School Calendar.md
> 230307 7am

- _school-information/Form Teacher List.md
> Update file: Form Teacher List.md

- _partners/Newsletters.md
- _partners/collection.yml
> 230418 del newsletter

- _data/navigation.yml
Hi Wai Wang. I'm adding the School Canteen subpage under School Information. I have discussed it with Xiaoying.
> School Canteen Subpage 

- _programmes/Direct School Admission.md
> Update 230503 DSA website

- _school-information/School Canteen.md
Hi Wai WAng, for your approval. Thank you,
> School Canteen Update #02

- _school-information/School Management.md
please approve one more. thanks
> updated SL

- _events/2024 Sec1 Information.md
> Pls approve

- _events/2024 Sec1 Information.md
> update sec1 website

- _announcement/Announcements.md
> Updated announcement

- _cca/CCA Schedule 2024.md
- _cca/collection.yml
- _programmes/Enrichment/CCA.md
- _school-information/2023 School Calendar.md
- _school-information/Form Teacher List.md
- _school-information/collection.yml
> updated FT and CCA schedule

- _information/Students/Useful Student Links.md
- _information/Teachers.md
> Updated Teachers' links

- _information/Events/2024 Sec 3 Meet the Parents Session (16 Feb 2024).md
> Remove Sec 3 MPS attachments

- _information/Direct School Admission.md
> Update on DSA again

- _information/Direct School Admission.md
- _information/Teachers.md
> DSA + ICT support

- _information/Direct School Admission.md
> DSa update

- index.md
add in register form link to the poster.
> Open House 2024

- _student-development/National Digital Literacy Programme (NDLP).md
I changed Zoom to Google Meet and removed betterinternet.sg url as its broken.
> Pls review ndlp

- _data/navigation.yml
- _information/Events/2025 Sec1 Meet The Parents Session (3 Jan 2025).md
- _our-people/Departments.md
- _our-people/collection.yml
- _our-school/Our Accolades/Staff Accolades.md
- _our-school/Our Accolades/Student Accolades.md
- _our-school/collection.yml
Remove Accolades section and Add a Page in Department. Write as 'to be updated' on the page as there are no info as yet.
> Remove Accolades and Department Page

- _student-development/CCA/Co Curricular Activities (CCA).md
Added an additional link for the CCA March Holiday Schedule. Requested by Huey Shan.
> CCA March Holiday Schedule 2025

- _student-development/CCA/Co Curricular Activities (CCA).md
Remove March Schedule and add in June Holidays Schedule.
> CCA Training Schedule June Holidays 2025
